### ISSUE TITLE
Consumer problems

### ISSUE THREAD

**Issue by DonatasD** [jhalliday/csc8101#4]
My Consumer seems to start the job properly and do the work. However, it does not consume all the messages from queue.
-- Meters ----------------------------------------------------------------------
throughput
             count = 457546
         mean rate = 4836.02 events/second
     1-minute rate = 4113.17 events/second
     5-minute rate = 2027.04 events/second
    15-minute rate = 1347.94 events/second

 INFO [myclient_ip-172-31-11-102-1423232252518-a037b72d_watcher_executor] (Logging.scala:68) - [myclient_ip-172-31-11-102-1423232252518-a037b72d], stopping watcher executor thread for consumer myclient_ip-172-31-11-102-1423232252518-a037b72d

As you can see myclient group have not consumed all the messages it had to.

ubuntu@ip-172-31-11-102:~/Big-data-cassandra$ ~/kafka/bin/kafka-run-class.sh kafka.tools.ConsumerOffsetChecker --zkconnect localhost:2181 --group myclient
Group           Topic                          Pid Offset          logSize         Lag             Owner
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
myclient        csc8101                        0   268803          50489553        50220750        none
myclient        csc8101                        1   259671          49879429        49619758        none
myclient        csc8101                        2   259346          50039695        49780349        none
myclient        csc8101                        3   237359          49591323        49353964        none

**Comment by DonatasD** [comment]
Was actually getting exception from parsing data from Kafka. 
My suggestion is to use try catch clauses to get notified about exceptions in handle method.

**Comment by DonatasD** [comment]
com.datastax.driver.core.exceptions.SyntaxError: line 1:99 missing EOF at 'nantes'
16671 [01/May/1998:17:47:52 +0000] "GET /french/venues/javascript:finddist('Nantes')/ HTTP/1.0" 404 332

**Comment by DonatasD** [comment]
This error is indicates incorrect query.

**Comment by mdanilakis** [comment]
Same here! I think its something that has to do with the single quote characters! What is the solution to that?

**Comment by DonatasD** [comment]
Yes you are right it closes you query single quote and gives error.
Try using QueryBuilder it worked for me:
http://www.datastax.com/documentation/developer/java-driver/2.0/java-driver/reference/queryBuilder_r.html

**Comment by mdanilakis** [comment]
Yes i was thinking something like .replaceAll("'","''");
But QueryBuilder seems more correct!
